pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build -c $(buildConfiguration)
  displayName: 'Build project'

steps:
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'
  displayName: 'Create nupkg'

- task: CopyFiles@2
  inputs:
    contents: '**\*.nupkg'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
    overWrite: true
  displayName: 'Copy nuget package to artifact staging'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget'