# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: 1.1.$(Rev:r)
  
pool:
  vmImage: 'vs2017-win2016'

steps:

- script: dotnet build  
  displayName: 'Build project'

- script: dotnet pack -c Release --no-build /p:PackageVersion=$(Build.BuildNumber)
  displayName: 'Pack nuget'
